### ISSUE TITLE
Retry connection to matrix server

### ISSUE THREAD

**Issue by nivekuil** [turt2live/matrix-bot-sdk#92] opened 2020-10-18 10:52 UTC
## The problem to solve

The matrix bot sdk seems to only try connecting to the server once, and doesn't retry, so if the bridges and synapse are started at the same time (e.g. in docker swarm, which expects applications to handle retry logic themselves) then the bridge just errors instantly from not being able to resolve the hostname, leaving it to the downstream consumer to properly handle it.

## Proposed solution

I took a look and it doesn't seem like the request library this uses has a built-in way to do retries, so this probably goes along with #90. If got is chosen, that has nice facilities for handling retries: https://github.com/sindresorhus/got#retry

## Alternatives

It could make sense to leave it to the downstream consumer to properly handle this stuff, but I think it would be better if this were handled upstream with the goal of keeping the matrix bot stuff as easy to use as possible. I don't think there is any real harm in retrying at least a few times for a few minutes.

**Comment by turt2live** [comment] 2022-05-30 03:24
Duplicate of https://github.com/turt2live/matrix-bot-sdk/issues/18

**Closed by turt2live** 2022-05-30 03:24 UTC
